# -*- coding: utf-8 -*-
"""To-Do-List-ProgBasica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9oD5Mco46iRFPrpGHOpiAfXNFvutILU
"""

tarefas = []

def adicionar_tarefa():
    # Pede ao usuário o texto da nova tarefa
    descricao = input("Digite a nova tarefa: ")
    # Cria um dicionário representando a tarefa
    tarefa = {
        "descricao": descricao,   # texto da tarefa
        "concluida": False        # por padrão, começa como não concluída
    }
    # Adiciona a tarefa à lista de tarefas
    tarefas.append(tarefa)
    # Confirma para o usuário
    print(f"Tarefa adicionada: {descricao}")

def listar_tarefas():
    # Se não houver nenhuma tarefa na lista
    if not tarefas:
        print("Nenhuma tarefa adicionada ainda.")
    else:
        print("\nSuas tarefas:")
        # Percorre a lista de tarefas com índice
        for i, tarefa in enumerate(tarefas, start=1):
            # Define um marcador para mostrar se a tarefa está concluída ou não
            # "[X]" para concluída, "[ ]" para pendente
            status = "[X]" if tarefa["concluida"] else "[ ]"
            # Mostra número, status e descrição da tarefa
            print(f"{i}. {status} {tarefa['descricao']}")
        # Linha em branco só para separar visualmente
        print()

def marcar_tarefa_concluida():
    # Primeiro mostramos as tarefas, para o usuário ver os números
    listar_tarefas()

    # Se não tiver tarefas, não faz sentido continuar
    if not tarefas:
        return

    # Pede o número da tarefa a ser marcada como concluída
    numero = input("Digite o número da tarefa que deseja marcar como concluída: ")

    # Verifica se o que foi digitado é um número
    if not numero.isdigit():
        print("Você precisa digitar um número válido.")
        return


    # Converte o texto para inteiro
    indice = int(numero) - 1  # -1 porque a lista começa em 0

    # Verifica se o número está dentro do intervalo de tarefas existentes
    if 0 <= indice < len(tarefas):
        # Marca a tarefa como concluída
        tarefas[indice]["concluida"] = True
        # Mostra qual tarefa foi marcada
        print(f"Tarefa concluída: {tarefas[indice]['descricao']}")
    else:
        # Se o número não corresponde a nenhuma tarefa
        print("Número de tarefa inválido.")


def remover_tarefa():
    # Mostramos as tarefas atuais
    listar_tarefas()

    # Se não tiver tarefas, não há o que remover
    if not tarefas:
        return

    # Pede o número da tarefa a ser removida
    numero = input("Digite o número da tarefa que deseja remover: ")

    # Verifica se o que foi digitado é um número
    if not numero.isdigit():
        print("Você precisa digitar um número válido.")
        return

    # Converte o texto para inteiro
    indice = int(numero) - 1  # -1 porque a lista começa em 0

    # Verifica se o índice é válido
    if 0 <= indice < len(tarefas):
        # Guarda a tarefa removida só para mostrar na mensagem
        tarefa_removida = tarefas.pop(indice)  # remove e retorna a tarefa
        print(f"Tarefa removida: {tarefa_removida['descricao']}")
    else:
        print("Número de tarefa inválido.")


def menu():
    # Loop infinito até o usuário escolher sair
    while True:
        print("=== TO-DO LIST ===")
        print("1 - Adicionar tarefa")
        print("2 - Listar tarefas")
        # NOVA OPÇÃO: marcar como concluída
        print("3 - Marcar tarefa como concluída")
        # NOVA OPÇÃO: remover tarefa
        print("4 - Remover tarefa")
        print("5 - Sair")

        # Pede a opção do usuário
        opcao = input("Escolha uma opção: ")

        # Verifica qual opção foi escolhida e chama a função correspondente
        if opcao == "1":
            adicionar_tarefa()
        elif opcao == "2":
            listar_tarefas()
        elif opcao == "3":
            marcar_tarefa_concluida()
        elif opcao == "4":
            remover_tarefa()
        elif opcao == "5":
            print("Saindo... Até mais!")
            break
        else:
            print("Opção inválida, tente novamente.")

        # Linha de separação visual entre um ciclo do menu e outro
        print("-" * 30)


# Garante que o menu só seja chamado se o arquivo for executado diretamente
if __name__ == "__main__":
    menu()